# Generated by Django 6.0.2 on 2026-03-09 21:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tache', '0001_initial'),
        ('utilisateur', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tache',
            name='created_by',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_NULL,to='utilisateur.profile'),
        ),
        migrations.AlterField(
            model_name='tache',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks_assigned', to='utilisateur.profile'),
        ),
    ]
