# Generated by Django 6.0.2 on 2026-03-10 00:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tache', '0002_tache_created_by_alter_tache_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='tache',
            name='date_completion',
            field=models.DateField(blank=True, null=True),
        ),
    ]
